spring:
  datasource:
    url: jdbc:postgresql://auth-postgres:5432/auth_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false

logging:
  level:
    root: WARN