spring:
  datasource:
    url: jdbc:postgresql://search-postgres:5432/search_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: kafka:9092