FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml ./

RUN pip install --upgrade pip && \
    pip install -e .

COPY . .

CMD sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"