version: "3.9"

services:

  # =========================
  # SEARCH DATABASE
  # =========================

  search-postgres:
    image: postgres:16.1
    container_name: search-postgres
    restart: always

    environment:
      POSTGRES_DB: search_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5435:5432"

    volumes:
      - search_pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d search_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =========================
  # ZOOKEEPER
  # =========================

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: always

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    ports:
      - "2181:2181"

  # =========================
  # KAFKA
  # =========================

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: always

    depends_on:
      - zookeeper

    ports:
      - "29092:29092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      ALLOW_PLAINTEXT_LISTENER: "yes"

  # =========================
  # SEARCH SERVICE
  # =========================

  search-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: search-service
    restart: always

    depends_on:
      search-postgres:
        condition: service_healthy
      kafka:
        condition: service_started

    ports:
      - "8085:8085"

    environment:
      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: jdbc:postgresql://search-postgres:5432/search_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

volumes:
  search_pg_data: